name: DeployDev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [ closed ]

jobs:

  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repo and install deps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd dev-bot/
            git checkout dev
            git pull origin dev
            npm i
            sudo systemctl restart devbot


