name: Deploy On Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repo and install deps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd calendar-bot-front/
            git checkout main
            git pull origin main
            npm i


