name: Deploy On Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm i

      - name: Compile
        run: npm run compile

      - name: Upload compile results
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-arctifact@v1
        with:
          name: build
      - name: Copy files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "build"
          target: "/home/centos/bot/prod"


