name: Node Calendar Bot

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: npm i

      - name: Do and check linters
      - run: npm run fix
      - run: npm run lint
